import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import HeaderOrganism from "@/organisms/header/header";
import FooterOrganism from "@/organisms/footer/footer";

const merriWeather = Merriweather({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriWeather.className}`}>
        <HeaderOrganism />
        {children}
        <FooterOrganism />
      </body>
    </html>
  );
}
