import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "../globals.css";
import HeaderOrganism from "@/organisms/header/header";
import FooterOrganism from "@/organisms/footer/footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Locale } from "@/utils/types";

const merriWeather = Merriweather({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = await params;
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body className={`${merriWeather.className}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <HeaderOrganism />
          {children}
          <FooterOrganism />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
